#!/bin/bash

if [[ "$1" == "debug" ]]; then
    OPTS="-ggdb3 -g3 -O0"
else
    OPTS="-O3"
fi

g++ -std=c++17 -Wall -Werror -o unittest ${OPTS} -D NO_RACK_DEPENDENCY -I../../src -I../include -I../../external \
    unittest.cpp    \
    ../../src/sapphire_granular_processor.cpp \
    ../../external/pffft.c \
    ../../external/fftpack.c \
    || exit 1

exit 0
