#!/bin/bash

if [[ "$1" == "debug" ]]; then
    OPTS="-ggdb3 -g3 -O0"
else
    OPTS="-O3"
fi

g++ -std=c++17 -Wall -Werror -o unittest ${OPTS} -D NO_RACK_DEPENDENCY -I../../src -I../include -Iairwindows \
    unittest.cpp    \
    ../../src/sapphire_calcparser.cpp    \
    ../../src/sapphire_prog_chaos.cpp    \
    airwindows/Galactic.cpp   \
    airwindows/GalacticProc.cpp   \
    || exit 1

exit 0
