#!/bin/bash

rm -f output/*.wav output/*.txt

echo "Building unit tests..."
./build || exit 1

echo "Running unit tests..."
./unittest all || exit 1

echo "Verifying output audio..."
sha256sum -c audio_hash.txt || exit 1

echo "Verifying granulizer output..."
diff {output,correct}/granule_identity_fade.txt || exit 1
diff {output,correct}/granule_identity_x.txt || exit 1
diff {output,correct}/granule_identity_y.txt || exit 1

echo "Unit tests: PASS"
exit 0
