#!/bin/bash

rm -f output/*.wav

echo "Building unit tests..."
./build || exit 1

echo "Running unit tests..."
./unittest all || exit 1

echo "Verifying output audio..."
sha256sum -c audio_hash.txt || exit 1

echo "Unit tests: PASS"
exit 0
