#!/bin/bash

if [[ "$1" == "debug" ]]; then
    OPTS="-ggdb3 -g3 -O0"
else
    OPTS="-O3"
fi

g++ -Wall -Werror -o unittest ${OPTS} -I../src -I../cmdline \
    unittest.cpp    \
    || exit 1

exit 0
