#!/bin/bash

RunPython()
{
    mypy --strict $1 || exit 1
    PYTHON_COLORS=0 python3 $* || exit 1
    return 0
}

echo "clean_presets: STARTING"
RunPython clean_sapphire_presets.py
echo "clean_presets: SUCCESS"
exit 0
