#!/bin/bash
Fail()
{
    echo "FAIL(codecheck): $1"
    exit 1
}

cppcheck --error-exitcode=9 --inline-suppr --suppress=constVariablePointer --suppress=constParameter --suppress=constParameterReference --suppress=unmatchedSuppression --suppress=missingIncludeSystem --suppress=missingInclude --suppress=useStlAlgorithm --suppress=unusedFunction --suppress=passedByValue --suppress=constVariableReference --suppress=variableScope --suppress=duplicateConditionalAssign -I ../src  --enable=all ../src || Fail "cppcheck frowns upon this code"
echo "The code checker is happy."
exit 0
