#!/bin/bash

echo "make_panels: STARTING"

python3 patch_elastika.py || exit 1

mypy --strict tubeunit_svg.py || exit 1
python3 tubeunit_svg.py || exit 1

mypy --strict chaos_svg.py || exit 1
python3 chaos_svg.py || exit 1

echo "make_panels: SUCCESS"
exit 0
