#!/bin/bash

RunPython()
{
    mypy --strict $1 || exit 1
    python3 $1 || exit 1
    return 0
}

echo "make_panels: STARTING"
RunPython tubeunit_svg.py
RunPython make_sapphire_svg.py
echo "make_panels: SUCCESS"
exit 0
