#!/bin/bash
RunPython()
{
    mypy --strict $1 || exit 1
    PYTHON_COLORS=0 python3 $* || exit 1
    return 0
}

./make_panels || exit 1

./clean_presets || exit 1

# Find a random local-minimum-energy state for the Nucleus module's particle gas simulation.
./nucleus_solver || exit 1

# Generate the optimized RK4 simulator for the Vina ribbon/mesh.
RunPython rk4/rk4_mesh_compiler.py

# Generate a custom force calculator for Elastika with unrolled loops.
./elastika_mesh_gen || exit 1

echo "Sapphire prebuild completed."
exit 0
