// DO NOT EDIT - THIS CODE IS AUTO-GENERATED BY: nukesolve.cpp
#pragma once
#include "nucleus_engine.hpp"
namespace Sapphire
{
    inline int SetMinimumEnergy(NucleusEngine& engine)
    {
        const int n = static_cast<int>(engine.numParticles());
        if (n != 5) return 777;

        Particle& p0 = engine.particle(0);
        p0.vel = PhysicsVector::zero();
        p0.pos[0] = 0;
        p0.pos[1] = 0;
        p0.pos[2] = 0;
        p0.pos[3] = 0;

        Particle& p1 = engine.particle(1);
        p1.vel = PhysicsVector::zero();
        p1.pos[0] = 1.445020079612732;
        p1.pos[1] = 0.4829490184783936;
        p1.pos[2] = 0.135395735502243;
        p1.pos[3] = 0;

        Particle& p2 = engine.particle(2);
        p2.vel = PhysicsVector::zero();
        p2.pos[0] = -0.3826243281364441;
        p2.pos[1] = -0.631231427192688;
        p2.pos[2] = -0.1613524109125137;
        p2.pos[3] = 0;

        Particle& p3 = engine.particle(3);
        p3.vel = PhysicsVector::zero();
        p3.pos[0] = -2.350261449813843;
        p3.pos[1] = 0.4914562106132507;
        p3.pos[2] = 0.589307427406311;
        p3.pos[3] = 0;

        Particle& p4 = engine.particle(4);
        p4.vel = PhysicsVector::zero();
        p4.pos[0] = 1.097127676010132;
        p4.pos[1] = -0.2905585467815399;
        p4.pos[2] = -0.3641924262046814;
        p4.pos[3] = 0;

        return 0;
    }
}
