name: Build VCV Rack Plugin
on: [push, pull_request]

env:
  rack-sdk-version: 2.6.3
  rack-plugin-toolchain-dir: /home/build/rack-plugin-toolchain

defaults:
  run:
    shell: bash

jobs:

  build:
    name: ${{ matrix.platform }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/qno/rack-plugin-toolchain-win-linux
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        platform: [win-x64, lin-x64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: plugin-version-cache
        with:
          path: plugin.json
          key: ${{ github.sha }}-${{ github.run_id }}
      - name: Build plugin
        run: |
          export PLUGIN_DIR=$GITHUB_WORKSPACE
          export SAPPHIRE_ENABLE_WERROR=1
          pushd ${{ env.rack-plugin-toolchain-dir }}
          make plugin-build-${{ matrix.platform }}
          cd plugin-build && sha256sum *.vcvplugin > checksum_${{ matrix.platform }}.txt && cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ env.rack-plugin-toolchain-dir }}/plugin-build/*.vcvplugin
            ${{ env.rack-plugin-toolchain-dir }}/plugin-build/checksum_*.txt
          name: ${{ matrix.platform }}

  build-mac:
    name: mac
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        id: plugin-version-cache
        with:
          path: plugin.json
          key: ${{ github.sha }}-${{ github.run_id }}
      - name: Get Rack-SDK
        run: |
          pushd $HOME
          wget -O Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-${{ env.rack-sdk-version }}-mac-${{ matrix.platform }}.zip
          unzip Rack-SDK.zip
      - name: Build plugin
        run: |
          CROSS_COMPILE_TARGET_x64=x86_64-apple-darwin
          CROSS_COMPILE_TARGET_arm64=arm64-apple-darwin
          export RACK_DIR=$HOME/Rack-SDK
          export CROSS_COMPILE=$CROSS_COMPILE_TARGET_${{ matrix.platform }}
          export SAPPHIRE_ENABLE_WERROR=1
          make dep
          make dist
          cd dist && shasum -a 256 *.vcvplugin > checksum_mac-${{ matrix.platform }}.txt && cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            dist/*.vcvplugin
            dist/checksum_*.txt
          name: mac-${{ matrix.platform }}

  publish-release-build:
    name: Publish Release
    if: startsWith(github.ref, 'refs/tags/v2.') && github.repository_owner == 'cosinekitty'
    runs-on: ubuntu-latest
    needs: [build, build-mac]
    steps:
      - uses: actions/checkout@v4
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.CI_REF_NAME }}
          body: |
            Sapphire ${{ env.CI_REF_NAME }} for VCV Rack
          draft: false
          prerelease: false
      - uses: actions/download-artifact@v4
        with:
          path: _artifacts
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _artifacts/**/*
          tag: ${{ github.ref }}
          file_glob: true

  publish-prerelease-build:
    name: Publish Pre-Release
    if: startsWith(github.ref, 'refs/tags/rc2.') && github.repository_owner == 'cosinekitty'
    runs-on: ubuntu-latest
    needs: [build, build-mac]
    steps:
      - uses: actions/checkout@v4
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.CI_REF_NAME }}
          body: |
            Sapphire ${{ env.CI_REF_NAME }} for VCV Rack
          draft: false
          prerelease: true
      - uses: actions/download-artifact@v4
        with:
          path: _artifacts
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _artifacts/**/*
          tag: ${{ github.ref }}
          file_glob: true
